language: php

php:
 - 5.4
 - 5.5

before_script:
 - curl -s http://getcomposer.org/installer | php
 - php composer.phar install --dev --no-interaction

script:
 - mkdir -p build/logs
 - phpunit -c phpunit.xml

after_script:
 - php vendor/bin/coveralls -v

notifications:
 email:
  on_success: change
  on_failure: change
  recipients:
   - nat@nath.is
   - claudio.albertin@me.com