import secp from './util/secp.ts';
import MessageDispatcherService from './MessageDispatcherService.ts';
import Peer from './Peer.ts';
import Hash from './util/Hash.ts';
import Context from './Context.ts';
import { ConnectionProvider } from './NetworkProvider.ts';
import ConnectionService, { Connection } from './ConnectionService.ts';
import ConnectionSpec from './ConnectionSpec.ts';
import BridgingService from './BridgingService.ts';
import { arrConcat, arrEquals } from './util/buffer.ts';
import { getOrCreate } from './util/map.ts';
import { InfoMessage } from './messages.ts';

// TODO: Split into connected and unconnected nodes. This will help eliminate optionals.
export interface Node {
  hash: Hash;

  // Map from protocols to connections.
  connections: Map<
    string,
    { tryConnect(spec: string): void; conn?: Connection }
  >;

  // This should be set to the fastest connection ready for sending.
  defaultConn?: Connection;
  // Connection promise?

  lastInfoTime: number;
  handledProtocols?: string[];
  neighbors: Set<Node>;

  // Number of network hops required to reach this node.
  // A path to this node can be recursivly generated by generating a path to it's neighbors where neighbor.hops === node.hops - 1
  hops: number;
}

export default class NodeService {
  private nodes: Map<string, Node> = new Map();

  private selfHash: Hash;
  private selfNode: Node;

  constructor(private ctx: Context) {
    this.selfHash = this.computeNodeHash(
      secp.getPublicKey(ctx.config.selfPrivateKey),
      ctx.config.nodeNonce,
    );

    this.selfNode = this.lookup(this.selfHash);
    this.selfNode.hops = 0;
  }

  public getSelfHash() {
    return this.selfHash;
  }

  public getSelfNode() {
    return this.selfNode;
  }

  public getAll() {
    return [...this.nodes.values()];
  }

  public computeNodeHash(publicKey: Uint8Array, nonce: Uint8Array) {
    return Hash.digest(
      arrConcat(
        new Uint8Array([publicKey.byteLength & 0xFF]),
        publicKey,
        nonce,
      ),
    );
  }

  public lookup(hash: Hash) {
    const key = hash.toHex();
    let node = this.nodes.get(key);
    if (!node) {
      node = {
        hash,
        connections: new Map(),
        lastInfoTime: 0,
        neighbors: new Set(),
        hops: Infinity,
      };
      this.nodes.set(key, node);
    }
    return node;
  }

  public initConnectionViaBridge(bridge: Node, node: Node, protocol: string) {
    getOrCreate(node.connections, protocol, () => {
      const onListen = (spec: string) =>
        // TODO: Don't require bridge, but calculate the path to the node
        this.ctx.get(BridgingService).sendConnSpec(bridge, node.hash, {
          protocol,
          data: spec,
        });
      const onNewConn = (provider: ConnectionProvider) =>
        this.ctx.get(ConnectionService).initConnection(protocol, provider);

      return this.ctx.config.networkProvider.protocols.get(protocol)!.create(
        onListen,
        onNewConn,
      );
    });
  }

  public addConnection(node: Node, protocol: string, conn: Connection) {
    const connObj = getOrCreate(
      node.connections,
      protocol,
      () => ({
        tryConnect: () => {
          throw new Error(`Connection already established`);
        },
      }),
    );
    if (connObj.conn) {
      throw new Error(
        `Two connections opened to node ${node.hash.toHex()} with same protocol ${protocol}`,
      );
    }
    connObj.conn = conn;

    if (node.defaultConn) {
      this.updateDefaultConn(node);
    } else {
      node.defaultConn = conn;
    }
  }

  public removeConnection(node: Node, protocol: string, conn: Connection) {
    if (node.connections.get(protocol)?.conn !== conn) {
      throw new Error(
        `Trying to remove connection on node ${node.hash.toHex()} with protocol ${protocol} but it doesn't match what's expected`,
      );
    }
    node.connections.delete(protocol);
    if (node.defaultConn === conn) {
      this.updateDefaultConn(node);
    }
  }

  private updateDefaultConn(node: Node) {
    let bestScore = Infinity;
    for (const [_protocol, { conn }] of node.connections) {
      if (conn) {
        const score = conn.ping.count ? conn.ping.sum / conn.ping.count : 1e9;
        if (score < bestScore) {
          bestScore = score;
          node.defaultConn = conn;
        }
      }
    }
  }

  public handleInfoMessage(
    conn: Connection,
    msg: InfoMessage,
  ) {
    const node = conn.node;

    node.neighbors.clear();
    node.hops = Infinity;
    msg.neighbors.forEach((neighbor) => {
      const neighborNode = this.lookup(neighbor.node_hash);
      neighborNode.handledProtocols = neighbor.handled_protocols;

      neighborNode.neighbors.add(node);
      node.neighbors.add(neighborNode);

      node.hops = Math.min(node.hops, neighborNode.hops + 1);
    });

    node.neighbors.forEach((neighborNode) =>
      neighborNode.hops = Math.min(neighborNode.hops, node.hops + 1)
    );
  }

  public connectViaBridge(bridge: Node, toNode: Node) {
    if (!toNode.handledProtocols) {
      throw new Error(
        `Cannot bridge to node ${toNode.hash.toHex()} because we don't know it's handled protocols`,
      );
    }
    const sharedProtocols = toNode.handledProtocols.filter((protocol) =>
      this.ctx.config.networkProvider.protocols.has(protocol)
    );
    if (sharedProtocols.length === 0) {
      throw new Error(
        `No shared protocols for communicating with node ${toNode.hash.toHex()}; I have ${
          Object.keys(this.ctx.config.networkProvider.protocols).join(',')
        } and remote node has ${toNode.handledProtocols.join(',')}`,
      );
    }

    sharedProtocols.forEach((protocol) => {
      const onListen = (spec: string) =>
        this.ctx.get(BridgingService).sendConnSpec(bridge, toNode.hash, {
          protocol,
          data: spec,
        });
      const onNewConn = (provider: ConnectionProvider) =>
        this.ctx.get(ConnectionService).initConnection(protocol, provider);

      this.ctx.config.networkProvider.protocols.get(protocol)!.create(
        onListen,
        onNewConn,
      );
    });
  }
}
