import Hash, { HashPrimitive } from './util/Hash.ts';
import Context from './Context.ts';
import { ConnectionProvider } from './NetworkProvider.ts';
import ConnectionService, { Connection } from './ConnectionService.ts';
import BridgingService from './BridgingService.ts';
import { getOrCreate } from './util/map.ts';
import KeyService from './KeyService.ts';
// import { debugSetEpochBaseTime } from '~/sbl/EpochContract.ts';
import {
  BlockFact,
  Fact,
  FactBase,
  FactSource,
  FactType,
  InfoRequestFact,
  NodeInfoFact,
} from '~/sbl/FactMeta.ts';
import NetworkService from '~/sbl/NetworkService.ts';
import { InfoRequest, NodeInfo } from '~/sbl/messages.ts';
import FactService from '~/sbl/FactService.ts';
import ClockService from '~/sbl/ClockService.ts';
import { todo } from '~/sbl/util/functional.ts';
import InfoService from '~/sbl/InfoService.ts';

// Bitcoin makes these attacks more difficult by only making an outbound connection to one IP address per /16 (x.y.0.0).

// Never sample from nodes; they could easily be overwhelmed by spamming NodeInfo packets

export interface RemoteNode {
  isRemote: true;

  infoFact?: NodeInfoFact;

  // TODO: Convert these to arrays so we can sample from them more easily

  // The set of currently connected connections
  connections: Set<Connection>;

  // Generated from this node's info packet and neighbors' info packets.
  neighbors: Set<Node>;

  // Number of network hops required to reach this node.
  // A path to this node can be recursively generated by generating a path to it's neighbors where neighbor.hops === node.hops - 1
  hops: number;

  knownFacts: Set<Fact>;

  // TODO: Filter this by canonicality
  producedBlocks: Set<BlockFact>;

  // Trust increases by 1/day
  // Trust decreases when nodes do suspicious things (we should also publish the suspicious things to our peers)
  // If trust is less than -1, disconnect
  // Only connect to peers where trust is greater than 0
  trust: number;

  // Altruism increases when we recieve helpful facts from the node
  // Altruism decreases when we send (hopefully helpful) facts to the node
  // We publish to positively altruistic nodes
  altruism: number;
}

export interface SelfNode extends
  Pick<
    RemoteNode,
    | 'infoFact'
    | 'neighbors'
    | 'hops'
    | 'producedBlocks'
  > {
  isRemote: false;
}

export type Node = SelfNode | RemoteNode;

export default class NodeService {
  private selfNode: SelfNode;
  private nodes: Map<HashPrimitive, Node> = new Map();

  constructor(private ctx: Context) {
    this.selfNode = {
      isRemote: false,
      neighbors: new Set(),
      hops: 0,
      producedBlocks: new Set(),
    };
    this.nodes.set(
      Hash.digest(this.ctx.get(KeyService).getSelfPublicKey()).toPrimitive(),
      this.selfNode,
    );
  }

  public getSelfNode() {
    return this.selfNode;
  }

  public get(publicKey: Uint8Array): Node | undefined {
    return this.nodes.get(Hash.digest(publicKey).toPrimitive());
  }

  public getOrCreate(publicKey: Uint8Array): Node {
    const hash = Hash.digest(publicKey);
    let node = this.nodes.get(hash.toPrimitive());
    if (node === undefined) {
      node = {
        isRemote: true,
        connections: new Set(),
        neighbors: new Set(),
        hops: Infinity,
        knownFacts: new Set(),
        producedBlocks: new Set(),
        trust: 0,
        altruism: 0,
      };
      this.nodes.set(hash.toPrimitive(), node);
    }
    return node;
  }

  public getAll() {
    return [...this.nodes.values()];
  }

  public getNeighbors() {
    return [...this.nodes.values()].flatMap((x) =>
      x.infoFact !== undefined
        ? [this.ctx.get(FactService).getPublicKey(x.infoFact)]
        : []
    );
  }

  // private updateDefaultConn(node: Node) {
  //   let bestScore = Infinity;
  //   for (const [_protocol, { conn }] of node.connections) {
  //     if (conn) {
  //       const score = conn.ping.count ? conn.ping.sum / conn.ping.count : 1e9;
  //       if (score < bestScore) {
  //         bestScore = score;
  //         node.defaultConn = conn;
  //       }
  //     }
  //   }
  // }

  public connectTo(node: Node) {
    const bridges = [...node.neighbors].filter((x) =>
      x.isRemote && x.connections.size !== 0
    );
    if (bridges.length === 0) {
      throw new Error(`No connection available to node!`);
    }
    const selectedBridge = bridges[
      Math.floor(
        bridges.length * this.ctx.config.entropyProvider.randomNumber(),
      )
    ];
    if (!selectedBridge.isRemote) {
      throw new Error(`Internal error!`);
    }
    const conns = [...selectedBridge.connections];
    const selectedConn = conns[
      Math.floor(
        conns.length * this.ctx.config.entropyProvider.randomNumber(),
      )
    ];
  }

  public createInfoFact(base: FactBase): NodeInfoFact {
    const fact = Object.assign(
      base,
      NodeInfo.decode(base.message),
      { type: FactType.NodeInfo as const },
    );

    if (fact.network !== this.ctx.config.network) {
      throw new Error(
        `Mismatched networks! ${fact.network} !== ${this.ctx.config.network}`,
      );
    }

    if (fact.userdata) {
      // const { epochStartTime } = JSON.parse(msg.userdata);
      // if (epochStartTime) {
      //   debugSetEpochBaseTime(epochStartTime);
      // }
    }

    const publicKey = this.ctx.get(FactService).getPublicKey(base);
    const node = this.getOrCreate(publicKey);
    node.infoFact = fact;

    node.neighbors.clear();
    node.hops = Infinity;
    for (const neighbor of fact.neighbors) {
      const neighborNode = this.getOrCreate(neighbor);

      neighborNode.neighbors.add(node);
      node.neighbors.add(neighborNode);

      node.hops = Math.min(node.hops, neighborNode.hops + 1);
    }

    for (const neighborNode of node.neighbors) {
      neighborNode.hops = Math.min(neighborNode.hops, node.hops + 1);
    }

    return fact;
  }

  public createRequestFact(base: FactBase): InfoRequestFact {
    const fact = Object.assign(
      base,
      InfoRequest.decode(base.message),
      { type: FactType.InfoRequest as const },
    );

    this.ctx.get(ClockService).setTimeout(
      () => {
        if (fact.path.length === 0) {
          const info = this.ctx.get(InfoService).makeInfo();
          this.ctx.get(FactService).emit(
            info,
            NodeInfo,
            FactType.NodeInfo,
            fact.fromNodes,
          );
        } else if (fact.path.length === 1) {
          const infoFact = this.get(fact.path[0])?.infoFact;
          if (infoFact === undefined) {
            throw new Error(`Unknown node`);
          }
          this.ctx.get(FactService).sendTo(infoFact, fact.fromNodes);
        } else {
          // TODO: Handle this case
          todo();
        }

        this.ctx.get(FactService).forget(fact);
      },
      0,
    );

    return fact;
  }
}
