import Hash, { HashPrimitive } from './util/Hash.ts';
import Context from './Context.ts';
import { ConnectionProvider } from './NetworkProvider.ts';
import ConnectionService, { Connection } from './ConnectionService.ts';
import BridgingService from './BridgingService.ts';
import { getOrCreate } from './util/map.ts';
import KeyService from './KeyService.ts';
// import { debugSetEpochBaseTime } from '~/sbl/EpochContract.ts';
import {
  BlockFact,
  Fact,
  FactBase,
  FactType,
  NodeInfoFact,
} from '~/sbl/FactMeta.ts';
import NetworkService from '~/sbl/NetworkService.ts';
import { NodeInfo } from '~/sbl/messages.ts';
import FactService from '~/sbl/FactService.ts';

// Bitcoin makes these attacks more difficult by only making an outbound connection to one IP address per /16 (x.y.0.0).

// Never sample from nodes; they could easily be overwhelmed by spamming NodeInfo packets

export interface Node {
  infoFact?: NodeInfoFact;

  // TODO: Convert these to arrays so we can sample from them more easily

  // The set of currently connected connections
  connections: Set<Connection>;

  // Generated from this node's info packet and neighbors' info packets.
  neighbors: Set<Node>;

  // Number of network hops required to reach this node.
  // A path to this node can be recursively generated by generating a path to it's neighbors where neighbor.hops === node.hops - 1
  hops: number;

  knownFacts: Set<Fact>;

  // TODO: Filter this by canonicality
  producedBlocks: Set<BlockFact>;

  // Trust increases by 1/day
  // Trust decreases when nodes do suspicious things (we should also publish the suspicious things to our peers)
  // If trust is less than -1, disconnect
  // Only connect to peers where trust is greater than 0
  trust: number;

  // Altruism increases when we recieve helpful facts from the node
  // Altruism decreases when we send (hopefully helpful) facts to the node
  // We publish to positively altruistic nodes
  altruism: number;
}

export default class NodeService {
  private nodes: Map<HashPrimitive, Node> = new Map();

  private selfNode: Node;

  constructor(private ctx: Context) {
    this.selfNode = this.getOrCreate(
      this.ctx.get(KeyService).getSelfPublicKey(),
    );
    this.selfNode.hops = 0;
  }

  public getSelfNode() {
    return this.selfNode;
  }

  public get(publicKey: Uint8Array): Node | undefined {
    return this.nodes.get(Hash.digest(publicKey).toPrimitive());
  }

  public getOrCreate(publicKey: Uint8Array): Node {
    const hash = Hash.digest(publicKey);
    let node = this.nodes.get(hash.toPrimitive());
    if (node === undefined) {
      node = {
        connections: new Set(),
        neighbors: new Set(),
        hops: Infinity,
        knownFacts: new Set(),
        producedBlocks: new Set(),
        trust: 0,
        altruism: 0,
      };
      this.nodes.set(hash.toPrimitive(), node);
    }
    return node;
  }

  public getNeighbors() {
    return [...this.nodes.values()].flatMap((x) =>
      x.infoFact !== undefined
        ? [this.ctx.get(FactService).getPublicKey(x.infoFact)]
        : []
    );
  }

  // private updateDefaultConn(node: Node) {
  //   let bestScore = Infinity;
  //   for (const [_protocol, { conn }] of node.connections) {
  //     if (conn) {
  //       const score = conn.ping.count ? conn.ping.sum / conn.ping.count : 1e9;
  //       if (score < bestScore) {
  //         bestScore = score;
  //         node.defaultConn = conn;
  //       }
  //     }
  //   }
  // }

  public createFact(base: FactBase): NodeInfoFact {
    const msg = NodeInfo.decode(base.message);

    if (msg.network !== this.ctx.config.network) {
      throw new Error(
        `Mismatched networks! ${msg.network} !== ${this.ctx.config.network}`,
      );
    }

    if (msg.userdata) {
      // const { epochStartTime } = JSON.parse(msg.userdata);
      // if (epochStartTime) {
      //   debugSetEpochBaseTime(epochStartTime);
      // }
    }

    const publicKey = this.ctx.get(FactService).getPublicKey(base);
    const node = this.getOrCreate(publicKey);

    node.neighbors.clear();
    node.hops = Infinity;
    msg.neighbors.forEach((neighbor) => {
      const neighborNode = this.getOrCreate(neighbor);

      neighborNode.neighbors.add(node);
      node.neighbors.add(neighborNode);

      node.hops = Math.min(node.hops, neighborNode.hops + 1);
    });

    node.neighbors.forEach((neighborNode) =>
      neighborNode.hops = Math.min(neighborNode.hops, node.hops + 1)
    );

    node.infoFact = Object.assign(base, msg, {
      type: FactType.NodeInfo as const,
    });
    return node.infoFact;
  }
}
