import echoWasmUrl from './fixtures/echo.wasm?url';
import { makeRecordOutput } from 'scaffold.io/contracts/RecordContract.ts';
import type { Scaffold } from 'scaffold.io/Scaffold.ts';
import { Hash } from 'scaffold.io/util/Hash.ts';
import {
  JS_COMPILER_CONTRACT,
  makeJsCompilerContract,
} from 'scaffold.io/contracts/JsCompilerContract.ts';
import type { Lang } from './examples/index.ts';

// The JS compiler is not shipped in the scaffold library bundle -- it lives in
// src/ but is excluded from the npm build, and the demo (which resolves
// `scaffold.io` straight to src/ via Vite) registers it here. These are the
// committed content hashes of the well-known WASM blob blocks the compiled JS
// contract stacks; they mirror well-known-blocks/<name>/dist/hash.json
// (`blobHash`). Regenerated by `deno task build:well-known` -- keep in sync.
const WASI_SHIM_BLOB_HASH = 'c916f47bd6616cd6ecedb4df2902e5737af597311fd9cd23aff5a352e18c38b6';
const QUICKJS_BLOB_HASH = '9b23f03580b6dcd7b4006f843c1bf635beba80b71b95170d415c44c876a21e21';
const JSON_WB_BLOB_HASH = '250da5f0c74aec9f32c0075cdc2aedaf4922ee7f33102a9b4ca69b897987ef84';

/**
 * Register the JS compiler contract on `scaffold` and return its hash. The
 * blob hashes are committed constants (the browser has no filesystem to read
 * well-known-blocks/<name>/dist/hash.json). Invoke the returned hash like any
 * contract: `put({ contract, params: { files: { '/main.js': source } } })`.
 *
 * Note: to actually execute the compiled contract the well-known blob blocks
 * (wasi-shim, QuickJS, json-wb) must also be resolvable -- seeded into the
 * store or fetched from peers. The demo does not seed them yet (Workstream C),
 * so this hash is registered but the language tabs still invoke the echo
 * placeholder below.
 */
export function registerJsCompiler(scaffold: Scaffold): Hash {
  scaffold.registerContract(
    JS_COMPILER_CONTRACT,
    makeJsCompilerContract({
      shimBlobHash: () => Hash.fromHex(WASI_SHIM_BLOB_HASH),
      quickjsBlobHash: () => Hash.fromHex(QUICKJS_BLOB_HASH),
      jsonWbBlobHash: () => Hash.fromHex(JSON_WB_BLOB_HASH),
    }),
  );
  return JS_COMPILER_CONTRACT;
}

// Bottom-of-stack marker required by WasmContractPlugin for single-module
// contracts. See docs/protocol/wasm-abi.md#stacking.
const LAYERS_DEFAULT = new TextEncoder().encode('[{}]');

let cachedEchoBytes: Uint8Array | undefined;

async function loadEchoBytes(): Promise<Uint8Array> {
  if (cachedEchoBytes) return cachedEchoBytes;
  const response = await fetch(echoWasmUrl);
  if (!response.ok) {
    throw new Error(`Failed to load echo.wasm fixture: ${response.status}`);
  }
  cachedEchoBytes = new Uint8Array(await response.arrayBuffer());
  return cachedEchoBytes;
}

/**
 * Publishes the C0 echo `.wasm` as a contract block onto the given Scaffold
 * and returns the published block hash. Until real per-language compiler
 * contracts exist (Workstream C), every language tab uses this same hash --
 * the echo contract simply emits the input params as an output, which is
 * enough for the UI to demonstrate the full compile + invoke roundtrip.
 */
export async function publishEchoContract(scaffold: Scaffold): Promise<Hash> {
  const bytes = await loadEchoBytes();
  // The echo contract block carries two custom record outputs ("wasm" and
  // "wasm_layers"); neither pattern matches the unified put/send shapes,
  // so we drive DraftManager directly.
  const draftManager = scaffold.context.draftManager;
  const draft = draftManager.addReady({
    claims: [],
    outputs: [
      makeRecordOutput('wasm', bytes),
      makeRecordOutput('wasm_layers', LAYERS_DEFAULT),
    ],
    declaredWeight: 1,
  });
  const result = draftManager.solidify([draft]);
  if (!result.ok) {
    throw new Error(
      'publishEchoContract: DraftManager.solidify returned no block (parked or awaitingAnchor)',
    );
  }
  return result.block.hash;
}

/** Map of language id -> compiler block hash for the active Scaffold. */
export type CompilerHashes = Record<Lang, Hash | null>;

/**
 * Build the per-language compiler-hash map. Until real compilers exist,
 * every entry points at the same echo block.
 */
export function buildCompilerHashes(echoHash: Hash): CompilerHashes {
  return {
    typescript: echoHash,
    javascript: echoHash,
    go: echoHash,
    python: echoHash,
    zig: echoHash,
    rust: echoHash,
    cpp: echoHash,
    c: echoHash,
    assemblyscript: echoHash,
    sqlite: echoHash,
  };
}
