// Generates src/well_known.zig with the canonical hash bytes for the
// RECORD_CONTRACT and HASH_CONTRACT well-known contracts. Run as:
//   deno run --allow-write scripts/wasm-determinism/generate_constants.ts
//
// Whenever the Scaffold hash algorithm or these well-known contract IDs
// change, re-run to keep the contract WASM in sync.

import { Hash } from '../../src/util/Hash.ts';
import { str2bin } from '../../src/util/buffer.ts';
import { HASH_CONTRACT, RECORD_CONTRACT } from '../../src/core/Block.ts';

function asZigBytes(hash: Hash, name: string): string {
  const bytes = hash.toBytes();
  const lines: string[] = [];
  for (let i = 0; i < bytes.length; i += 8) {
    const chunk: string[] = [];
    for (let j = i; j < Math.min(i + 8, bytes.length); j++) {
      chunk.push('0x' + bytes[j].toString(16).padStart(2, '0'));
    }
    lines.push('    ' + chunk.join(', ') + ',');
  }
  return `pub const ${name}: [32]u8 = .{\n${lines.join('\n')}\n};\n`;
}

// Sanity check: confirm we match the live source-of-truth constants from
// src/core/Block.ts so the contract and the host agree.
const recordExpected = Hash.digest(str2bin('result-contract'));
const hashExpected = Hash.digest(str2bin('hash-contract'));
if (!Hash.equals(RECORD_CONTRACT, recordExpected)) {
  throw new Error('RECORD_CONTRACT drift: src/core/Block.ts is out of sync');
}
if (!Hash.equals(HASH_CONTRACT, hashExpected)) {
  throw new Error('HASH_CONTRACT drift: src/core/Block.ts is out of sync');
}

const header = `// AUTO-GENERATED by scripts/wasm-determinism/generate_constants.ts.
// Do not edit by hand. Regenerate via deno task build-determinism-contract.
//
// These values must match the live constants in src/core/Block.ts.

`;

const body = asZigBytes(RECORD_CONTRACT, 'RECORD_CONTRACT') +
  '\n' + asZigBytes(HASH_CONTRACT, 'HASH_CONTRACT');

const outPath = new URL('./src/well_known.zig', import.meta.url);
await Deno.writeTextFile(outPath, header + body);
// deno-lint-ignore no-console
console.log(`Wrote ${outPath.pathname}`);
// deno-lint-ignore no-console
console.log(`  RECORD_CONTRACT: ${RECORD_CONTRACT.toHex()}`);
// deno-lint-ignore no-console
console.log(`  HASH_CONTRACT:   ${HASH_CONTRACT.toHex()}`);
