import { Hash, HashPrimitive } from './util/Hash.ts';
import { Context } from './Context.ts';
import { Connection } from './ConnectionService.ts';
import { KeyService } from './KeyService.ts';
import {
  Fact,
  FactBase,
  FactType,
  InfoRequestFact,
  NodeInfoFact,
} from './FactMeta.ts';
import { NetworkService } from './NetworkService.ts';
import { InfoRequest, NodeInfo } from './messages.ts';
import { FactService } from './FactService.ts';
import { ClockService } from './ClockService.ts';
import { todo } from './util/functional.ts';
import { InfoService } from './InfoService.ts';
import { SignalingService } from './SignalingService.ts';
import { mapPut } from './util/map.ts';

const emitInfoIntervalMs = 60000;
const infoExpirationMs = 10 * emitInfoIntervalMs;

// Bitcoin makes these attacks more difficult by only making an outbound connection to one IP address per /16 (x.y.0.0).

// Never sample from nodes; they could easily be overwhelmed by spamming NodeInfo packets

// TODO: Convert these to arrays so we can sample from them more easily

interface NodeCommon {
  publicKey: Uint8Array;

  infoFact?: NodeInfoFact;

  infoRequests: Set<InfoRequestFact>;

  // Generated from this node's info packet and neighbors' info packets.
  // TODO: Move this to Connection?
  neighbors: Set<Peer>;

  // Number of network hops required to reach this node.
  // A path to this node can be recursively generated by generating a path to it's neighbors where neighbor.hops === node.hops - 1
  hops: number;

  // TODO: Filter this by canonicality
  producedFacts: Set<Fact>;
}

export interface RemoteNode extends NodeCommon {
  isRemote: true;

  // The set of currently connected connections
  connections: Set<Connection>;

  // Trust increases by 1/day
  // Trust decreases when nodes do suspicious things (we should also publish the suspicious things to our peers)
  // If trust is less than -1, disconnect
  // Only connect to peers where trust is greater than 0
  trust: number;

  // Altruism increases when we recieve helpful facts from the node
  // Altruism decreases when we send (hopefully helpful) facts to the node
  // We publish to positively altruistic nodes
  altruism: number;
}

export interface SelfNode extends NodeCommon {
  isRemote: false;
}

// TODO: Rename to Peer
export type Peer = SelfNode | RemoteNode;

export class NodeService {
  private selfNode: SelfNode;
  private nodes: Map<HashPrimitive, Peer> = new Map();

  constructor(private ctx: Context) {
    this.selfNode = {
      publicKey: ctx.get(KeyService).getSelfPublicKey(),
      isRemote: false,
      infoRequests: new Set(),
      neighbors: new Set(),
      hops: 0,
      producedFacts: new Set(),
    };
    this.nodes.set(
      Hash.digest(ctx.get(KeyService).getSelfPublicKey()).toPrimitive(),
      this.selfNode,
    );

    ctx.get(ClockService).setPoissonInterval(
      () =>
        this.ctx.get(FactService).emit(
          this.ctx.get(InfoService).makeInfo(),
          NodeInfo,
          FactType.NodeInfo,
          true,
        ),
      emitInfoIntervalMs,
    );
  }

  public getSelfNode() {
    return this.selfNode;
  }

  public get(publicKey: Uint8Array): Peer | undefined {
    return this.nodes.get(Hash.digest(publicKey).toPrimitive());
  }

  public getOrCreate(publicKey: Uint8Array): Peer {
    const hash = Hash.digest(publicKey);
    let node = this.nodes.get(hash.toPrimitive());
    if (node === undefined) {
      node = {
        publicKey,
        isRemote: true,
        infoRequests: new Set(),
        neighbors: new Set(),
        hops: Infinity,
        producedFacts: new Set(),
        connections: new Set(),
        trust: 0,
        altruism: 0,
      };
      this.nodes.set(hash.toPrimitive(), node);

      this.ctx.get(ClockService).setTimeout(
        () =>
          this.ctx.get(FactService).emit(
            this.ctx.get(InfoService).makeInfo(),
            NodeInfo,
            FactType.NodeInfo,
            true,
          ),
        0,
      );
    }
    return node;
  }

  public getAll() {
    return [...this.nodes.values()];
  }

  public getNeighbors() {
    return [...this.nodes.values()].flatMap((x) =>
      x.infoFact !== undefined && this.isInfoValid(x.infoFact)
        ? [x.publicKey]
        : []
    );
  }

  // private updateDefaultConn(node: Node) {
  //   let bestScore = Infinity;
  //   for (const [_protocol, { conn }] of node.connections) {
  //     if (conn) {
  //       const score = conn.ping.count ? conn.ping.sum / conn.ping.count : 1e9;
  //       if (score < bestScore) {
  //         bestScore = score;
  //         node.defaultConn = conn;
  //       }
  //     }
  //   }
  // }

  public connectTo(node: RemoteNode) {
    if (node.connections.size !== 0) {
      return;
    }

    if (node.infoFact === undefined || !this.isInfoValid(node.infoFact)) {
      this.ctx.get(FactService).emit(
        { path: [node.publicKey] },
        InfoRequest,
        FactType.InfoRequest,
        true,
      );
      return;
    }

    const protocol = node.infoFact.protocols
      .map((x) => this.ctx.get(NetworkService).parseProtocol(x))
      .filter((x) => this.ctx.get(NetworkService).findProviderMatching(x))[0];
    if (protocol === undefined) {
      throw new Error(`No intersecting protocols!`);
    }

    if (
      this.ctx.get(SignalingService).isConnecting(node.publicKey, protocol.name)
    ) {
      return;
    }

    this.ctx.get(SignalingService).ingestSignal(node.publicKey, {
      protocolName: protocol.name,
      signalIdx: -1,
      signalData: '',
      isSelfInitiator: true,
    });
  }

  public pathTo(peer: Peer) {
    const counter = new Map<Connection, number>();
    for (const fact of peer.producedFacts) {
      mapPut(counter, fact.fromConnections[0], () => 1, (x) => x + 1);
    }

    let best: Connection | undefined;
    let count = 0;
    for (const [key, val] of counter) {
      if (val > count) {
        best = key;
        count = val;
      }
    }

    return best;
  }

  private findBridgeTo(node: Peer) {
    const bridges = [...node.neighbors].filter((x) =>
      x.isRemote && x.connections.size !== 0
    );
    if (bridges.length === 0) {
      throw new Error(`No connection available to node!`);
    }
    const selectedBridge = bridges[
      Math.floor(
        bridges.length * this.ctx.config.entropyProvider.randomNumber(),
      )
    ];
    if (!selectedBridge.isRemote) {
      throw new Error(`Internal error!`);
    }
    const conns = [...selectedBridge.connections];
    const selectedConn = conns[
      Math.floor(
        conns.length * this.ctx.config.entropyProvider.randomNumber(),
      )
    ];
    return selectedConn;
  }

  public createInfoFact(base: FactBase): NodeInfoFact {
    const fact = Object.assign(
      base,
      NodeInfo.decode(base.message),
      { type: FactType.NodeInfo as const },
    );

    if (fact.network !== this.ctx.config.network) {
      throw new Error(
        `Mismatched networks! ${fact.network} !== ${this.ctx.config.network}`,
      );
    }

    if (fact.userdata) {
      JSON.parse(fact.userdata);
    }

    if (!this.isInfoValid(fact)) {
      throw new Error(`Invalid info fact!`);
    }

    const publicKey = this.ctx.get(FactService).getPublicKey(base);
    const node = this.getOrCreate(publicKey);
    node.infoFact = fact;

    for (const request of node.infoRequests) {
      this.ctx.get(FactService).sendTo(fact, request.fromConnections);
    }
    node.infoRequests.clear();

    node.neighbors.clear();
    node.hops = Infinity;
    for (const neighbor of fact.neighbors) {
      const neighborNode = this.getOrCreate(neighbor);

      neighborNode.neighbors.add(node);
      node.neighbors.add(neighborNode);

      node.hops = Math.min(node.hops, neighborNode.hops + 1);

      if (neighborNode.isRemote) {
        this.connectTo(neighborNode);
      }
    }

    for (const neighborNode of node.neighbors) {
      neighborNode.hops = Math.min(neighborNode.hops, node.hops + 1);
    }

    if (node.isRemote) {
      this.connectTo(node);
    }

    return fact;
  }

  public createRequestFact(base: FactBase): InfoRequestFact {
    const fact = Object.assign(
      base,
      InfoRequest.decode(base.message),
      { type: FactType.InfoRequest as const },
    );

    this.ctx.get(ClockService).setTimeout(
      () => {
        this.ctx.get(FactService).forget(fact);

        let node: Peer | undefined;
        if (fact.path.length === 0) {
          node = this.selfNode;
        } else if (fact.path.length === 1) {
          node = this.get(fact.path[0]);
        } else {
          // TODO: Handle this case
          todo();
        }

        if (node !== undefined) {
          if (node.infoFact !== undefined && this.isInfoValid(node.infoFact)) {
            this.ctx.get(FactService).sendTo(
              node.infoFact,
              fact.fromConnections,
            );
          } else {
            node.infoRequests.add(fact);
          }
        }
      },
      0,
    );

    return fact;
  }

  private isInfoValid(info: NodeInfoFact) {
    const now = BigInt(this.ctx.config.timeProvider.now());
    return info.timestamp >= now - BigInt(infoExpirationMs) &&
      info.timestamp <= now;
  }
}
