import { Hash, HashPrimitive } from './util/Hash.ts';
import { Context } from './Context.ts';
import { Connection } from './ConnectionService.ts';
import { KeyService } from './KeyService.ts';
import { Fact, FactBase, FactType, PeerInfoFact } from './FactMeta.ts';
import { NetworkService } from './NetworkService.ts';
import { InfoRequest, PeerInfo } from './messages.ts';
import { FactService } from './FactService.ts';
import { ClockService } from './ClockService.ts';
import { SignalingService } from './SignalingService.ts';
import { mapPut } from './util/map.ts';
import { bin2hex } from './util/hex.ts';

const emitInfoIntervalMs = 60000;
const infoExpirationMs = 10 * emitInfoIntervalMs;

// Bitcoin makes these attacks more difficult by only making an outbound connection to one IP address per /16 (x.y.0.0).

// Never sample from nodes; they could easily be overwhelmed by spamming PeerInfo packets

// TODO: Convert these to arrays so we can sample from them more easily

// infoRequests: Set<InfoRequestFact>;

// Generated from this node's info packet and neighbors' info packets.
// TODO: Move this to Connection?
// neighbors: Set<Peer>;

// Number of network hops required to reach this node.
// A path to this node can be recursively generated by generating a path to it's neighbors where neighbor.hops === node.hops - 1
// hops: number;

export interface RemotePeer {
  isRemote: true;

  // The set of currently connected connections
  connections: Set<Connection>;

  knownFacts: Set<Fact>;

  // Trust increases by 1/day
  // Trust decreases when nodes do suspicious things (we should also publish the suspicious things to our peers)
  // If trust is less than -1, disconnect
  // Only connect to peers where trust is greater than 0
  trust: number;

  // TODO: Remove this (it should only be on a Connection)
  // Altruism increases when we recieve helpful facts from the node
  // Altruism decreases when we send (hopefully helpful) facts to the node
  // We publish to positively altruistic nodes
  altruism: number;
}

export interface AuthenticatedPeer {
  publicKey: Uint8Array;

  infoFact?: PeerInfoFact;

  // TODO: Filter this by canonicality
  producedFacts: Set<Fact>;
}

export interface SelfPeer extends AuthenticatedPeer {
  isRemote: false;
}

export type Peer = SelfPeer | (RemotePeer & AuthenticatedPeer);

export class PeerManager {
  private peers: Map<HashPrimitive, Peer> = new Map();

  constructor(private ctx: Context) {
    this.initSelfPeer();

    ctx.get(ClockService).setPoissonInterval(
      () =>
        this.ctx.get(FactService).emit(
          this.makeInfo(),
          PeerInfo,
          FactType.PeerInfo,
          true,
        ),
      emitInfoIntervalMs,
    );
  }

  private initSelfPeer() {
    const selfPublicKey = this.ctx.get(KeyService).getSelfPublicKey();
    this.peers.set(
      Hash.digest(selfPublicKey).toPrimitive(),
      {
        isRemote: false,
        publicKey: selfPublicKey,
        producedFacts: new Set(),
      } satisfies SelfPeer,
    );
  }

  public getPeer(publicKey: Uint8Array): Peer | undefined {
    return this.peers.get(Hash.digest(publicKey).toPrimitive());
  }

  public putPeer(publicKey: Uint8Array): Peer {
    const hash = Hash.digest(publicKey);
    let peer = this.peers.get(hash.toPrimitive());
    if (peer === undefined) {
      peer = {
        isRemote: true,
        connections: new Set(),
        knownFacts: new Set(),
        trust: 0,
        altruism: 0,
        publicKey,
        producedFacts: new Set(),
      } satisfies RemotePeer & AuthenticatedPeer;
      this.peers.set(hash.toPrimitive(), peer);
    }
    return peer;
  }

  public getAll() {
    return [...this.peers.values()];
  }

  public makeInfo(): PeerInfo {
    const conns = new Set(
      this.getAll().flatMap((x) => x.isRemote ? [...x.connections] : []),
    );

    return {
      timestamp: BigInt(this.ctx.config.timeProvider.now()),
      network: this.ctx.config.network,
      version: 1,
      userdata: this.ctx.config.userdata ?? '',
      bandwidth: Math.floor(40000 / (conns.size + 1)),
      protocols: this.ctx.get(NetworkService).getProtocolList(),
    };
  }

  // private updateDefaultConn(node: Node) {
  //   let bestScore = Infinity;
  //   for (const [_protocol, { conn }] of node.connections) {
  //     if (conn) {
  //       const score = conn.ping.count ? conn.ping.sum / conn.ping.count : 1e9;
  //       if (score < bestScore) {
  //         bestScore = score;
  //         node.defaultConn = conn;
  //       }
  //     }
  //   }
  // }

  public connectTo(peer: Peer) {
    if (!peer.isRemote) {
      return;
    }

    if (peer.connections.size !== 0) {
      return;
    }

    if (this.ctx.get(SignalingService).isConnecting(peer.publicKey)) {
      return;
    }

    if (peer.infoFact === undefined || !this.isInfoValid(peer.infoFact)) {
      return;
    }

    const candidates = peer.infoFact.protocols
      .filter((x) =>
        this.ctx.get(NetworkService).findProvider(undefined, x) !== undefined
      );
    if (candidates.length === 0) {
      throw new Error(`No intersecting protocols!`);
    }
    const srcProtocol = candidates[
      Math.floor(
        this.ctx.config.entropyProvider.randomNumber() * candidates.length,
      )
    ];
    const dstProtocol =
      this.ctx.get(NetworkService).findProvider(undefined, srcProtocol)!
        .providesProtocols[0];

    this.ctx.get(SignalingService).init(
      peer.publicKey,
      srcProtocol,
      dstProtocol,
    );
  }

  public pathTo(peer: Peer) {
    const counter = new Map<Connection, number>();
    for (const fact of peer.producedFacts) {
      if (fact.fromConnections.length !== 0) {
        mapPut(counter, fact.fromConnections[0], () => 1, (x) => x + 1);
      }
    }

    let best: Connection | undefined;
    let count = 0;
    for (const [key, val] of counter) {
      if (val > count) {
        best = key;
        count = val;
      }
    }

    console.log('PATH TO', bin2hex(peer.publicKey), best?.name);

    return best;
  }

  // private findBridgeTo(peer: Peer) {
  //   const bridges = [...peer.neighbors].filter((x) =>
  //     x.isRemote && x.connections.size !== 0
  //   );
  //   if (bridges.length === 0) {
  //     throw new Error(`No connection available to node!`);
  //   }
  //   const selectedBridge = bridges[
  //     Math.floor(
  //       bridges.length * this.ctx.config.entropyProvider.randomNumber(),
  //     )
  //   ];
  //   if (!selectedBridge.isRemote) {
  //     throw new Error(`Internal error!`);
  //   }
  //   const conns = [...selectedBridge.connections];
  //   const selectedConn = conns[
  //     Math.floor(
  //       conns.length * this.ctx.config.entropyProvider.randomNumber(),
  //     )
  //   ];
  //   return selectedConn;
  // }

  public createInfoFact(base: FactBase): PeerInfoFact {
    const fact = Object.assign(
      base,
      PeerInfo.decode(base.message),
      { type: FactType.PeerInfo as const },
    );

    if (fact.network !== this.ctx.config.network) {
      throw new Error(
        `Mismatched networks! ${fact.network} !== ${this.ctx.config.network}`,
      );
    }

    if (fact.userdata) {
      // TODO: Store on the fact
      JSON.parse(fact.userdata);
    }

    if (!this.isInfoValid(fact)) {
      throw new Error(`Invalid info fact!`);
    }

    const publicKey = this.ctx.get(FactService).getPublicKey(base);
    const peer = this.putPeer(publicKey);
    peer.infoFact = fact;

    // for (const request of peer.infoRequests) {
    //   this.ctx.get(FactService).sendTo(fact, request.fromConnections);
    // }
    // peer.infoRequests.clear();

    // peer.neighbors.clear();
    // peer.hops = Infinity;
    // for (const neighbor of fact.neighbors) {
    //   const neighborNode = this.getOrCreate(neighbor);

    //   neighborNode.neighbors.add(peer);
    //   peer.neighbors.add(neighborNode);

    //   peer.hops = Math.min(peer.hops, neighborNode.hops + 1);

    //   if (neighborNode.isRemote) {
    //     this.connectTo(neighborNode);
    //   }
    // }

    // for (const neighborNode of peer.neighbors) {
    //   neighborNode.hops = Math.min(neighborNode.hops, peer.hops + 1);
    // }

    this.connectTo(peer);

    this.ctx.get(FactService).publish(fact);

    return fact;
  }

  // public createRequestFact(base: FactBase): InfoRequestFact {
  //   const fact = Object.assign(
  //     base,
  //     InfoRequest.decode(base.message),
  //     { type: FactType.InfoRequest as const },
  //   );

  //   this.ctx.get(ClockService).setTimeout(
  //     () => {
  //       this.ctx.get(FactService).forget(fact);

  //       let peer: Peer | undefined;
  //       if (fact.path.length === 0) {
  //         peer = this.selfPeer;
  //       } else if (fact.path.length === 1) {
  //         peer = this.get(fact.path[0]);
  //       } else {
  //         // TODO: Handle this case
  //         todo();
  //       }

  //       if (peer !== undefined) {
  //         if (peer.infoFact !== undefined && this.isInfoValid(peer.infoFact)) {
  //           this.ctx.get(FactService).sendTo(
  //             peer.infoFact,
  //             fact.fromConnections,
  //           );
  //         } else {
  //           peer.infoRequests.add(fact);
  //         }
  //       }
  //     },
  //     0,
  //   );

  //   return fact;
  // }

  private isInfoValid(info: PeerInfoFact) {
    const now = BigInt(this.ctx.config.timeProvider.now());
    return info.timestamp >= now - BigInt(infoExpirationMs) &&
      info.timestamp <= now;
  }
}
